-- MySQL Script generated by MySQL Workbench
-- Sat Mar  3 15:32:57 2018
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema vueInst
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema vueInst
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `vueInst` DEFAULT CHARACTER SET utf8 ;
USE `vueInst` ;

-- -----------------------------------------------------
-- Table `vueInst`.`user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `vueInst`.`user` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `f_name` VARCHAR(45) NOT NULL,
  `s_name` VARCHAR(45) NOT NULL,
  `login` VARCHAR(20) NOT NULL,
  `password` VARCHAR(255) NOT NULL,
  `photo` VARCHAR(255) NULL,
  `private` ENUM('0', '1') NOT NULL DEFAULT '0',
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `vueInst`.`image`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `vueInst`.`image` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `description` TEXT NOT NULL,
  `date` DATETIME NOT NULL,
  `src` VARCHAR(255) NOT NULL,
  `user_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_image_user_idx` (`user_id` ASC),
  CONSTRAINT `fk_image_user`
    FOREIGN KEY (`user_id`)
    REFERENCES `vueInst`.`user` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `vueInst`.`subscribe`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `vueInst`.`subscribe` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `who` INT NOT NULL,
  `whom` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_subs_user1_idx` (`who` ASC),
  INDEX `fk_subs_user2_idx` (`whom` ASC),
  CONSTRAINT `fk_subs_user1`
    FOREIGN KEY (`who`)
    REFERENCES `vueInst`.`user` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_subs_user2`
    FOREIGN KEY (`whom`)
    REFERENCES `vueInst`.`user` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `vueInst`.`like`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `vueInst`.`like` (
  `id` INT NOT NULL,
  `user_id` INT NOT NULL,
  `image_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_likes_user1_idx` (`user_id` ASC),
  INDEX `fk_likes_image1_idx` (`image_id` ASC),
  CONSTRAINT `fk_likes_user1`
    FOREIGN KEY (`user_id`)
    REFERENCES `vueInst`.`user` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_likes_image1`
    FOREIGN KEY (`image_id`)
    REFERENCES `vueInst`.`image` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `vueInst`.`comment`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `vueInst`.`comment` (
  `id` INT NOT NULL,
  `user_id` INT NOT NULL,
  `image_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_likes_user1_idx` (`user_id` ASC),
  INDEX `fk_likes_image1_idx` (`image_id` ASC),
  CONSTRAINT `fk_likes_user10`
    FOREIGN KEY (`user_id`)
    REFERENCES `vueInst`.`user` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_likes_image10`
    FOREIGN KEY (`image_id`)
    REFERENCES `vueInst`.`image` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
